#!/usr/bin/env -S deno run --allow-read --allow-write
/**
 * Writes the generated artifacts:
 *   - traceability/matrix.generated.json   REQ <-> ADR <-> event <-> scenario <-> inbox source
 *   - adr/in-force.generated.md            accepted, not superseded
 *
 * DETERMINISTIC BY CONSTRUCTION. No timestamps, no clock reads, no map iteration order that
 * depends on the filesystem — CI runs this and fails on a diff, so any nondeterminism turns into
 * a permanently red build that looks like a stale file.
 */
import { parse as parseYaml } from "@std/yaml";
import { walk } from "@std/fs";
import { basename, relative } from "@std/path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const rel = (p: string) => relative(ROOT, p);
/** Templates and previously-generated artifacts are never inputs — otherwise gen feeds on itself. */
const isTemplate = (p: string) => basename(p).startsWith("_") || basename(p).includes(".generated.");

const HEADER = "GENERATED by tools/generate.ts — DO NOT EDIT. Run `deno task gen`.";

const CONTEXTS = ["ledger", "fulfillment", "billing", "fixed-assets", "ordering", "availability", "banking", "tax"];
const CODE_OF: Record<string, string> = {
  ledger: "LED",
  fulfillment: "FUL",
  billing: "BIL",
  "fixed-assets": "FA",
  ordering: "ORD",
  availability: "AVL",
  banking: "BNK",
  tax: "TAX",
};

function frontMatter(text: string) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return null;
  try {
    return { fm: (parseYaml(m[1]) ?? {}) as Record<string, unknown>, body: m[2] ?? "" };
  } catch {
    return null;
  }
}

async function filesIn(dir: string, ext: string): Promise<string[]> {
  const out: string[] = [];
  try {
    for await (const e of walk(`${ROOT}/${dir}`, { exts: [ext], includeDirs: false })) {
      if (!isTemplate(e.path)) out.push(e.path);
    }
  } catch { /* absent */ }
  return out.sort();
}

// ── load ────────────────────────────────────────────────────────────────────
interface Req {
  id: string;
  statement?: string;
  source?: string;
  status?: string;
  priority?: string;
  relates_to?: string[];
}

const reqs: (Req & { context: string })[] = [];
const events: { id: string; name?: string; producer?: string; consumers?: string[]; context: string }[] = [];

for (const ctx of CONTEXTS) {
  try {
    const y = parseYaml(await Deno.readTextFile(`${ROOT}/contexts/${ctx}/requirements.yaml`)) as
      | { requirements?: Req[] }
      | null;
    for (const r of y?.requirements ?? []) reqs.push({ ...r, context: ctx });
  } catch { /* absent */ }
  try {
    const y = parseYaml(await Deno.readTextFile(`${ROOT}/contexts/${ctx}/events.yaml`)) as
      | { events?: { id: string }[] }
      | null;
    for (const e of y?.events ?? []) events.push({ ...e, context: ctx } as (typeof events)[number]);
  } catch { /* absent */ }
}

const adrs: {
  id: string;
  title?: string;
  status?: string;
  date?: string;
  review_by?: string;
  contexts?: string[];
  relates_to?: string[];
  superseded_by?: string | null;
  supersedes?: string | null;
  y: string;
  file: string;
}[] = [];

for (const f of await filesIn("adr", ".md")) {
  const p = frontMatter(await Deno.readTextFile(f));
  if (!p) continue;
  // Y-statement: the first blockquote block after the front matter.
  const q = p.body.match(/(?:^|\n)((?:>[^\n]*\n?)+)/);
  const y = q
    ? q[1].split("\n").map((l) => l.replace(/^>\s?/, "").trim()).filter(Boolean).join(" ").trim()
    : "";
  adrs.push({ ...p.fm, y, file: rel(f) } as unknown as (typeof adrs)[number]);
}

const inbox: { file: string; title?: string; promotes_to: string[] }[] = [];
for (const f of await filesIn("inbox", ".md")) {
  const p = frontMatter(await Deno.readTextFile(f));
  if (!p) continue;
  const pt = p.fm.promotes_to;
  inbox.push({
    file: rel(f),
    title: p.fm.title as string | undefined,
    promotes_to: Array.isArray(pt) ? pt.map(String) : [],
  });
}

// scenarios by REQ tag
const scenarios: Record<string, string[]> = {};
for (const f of await filesIn("contexts", ".feature")) {
  const text = await Deno.readTextFile(f);
  for (const m of text.matchAll(/@(REQ-[A-Z]{2,3}-\d{3})/g)) {
    (scenarios[m[1]] ??= []).push(rel(f));
  }
}

// ── matrix ──────────────────────────────────────────────────────────────────
const rows = reqs
  .map((r) => ({
    id: r.id,
    context: r.context,
    context_code: CODE_OF[r.context],
    status: r.status ?? null,
    priority: r.priority ?? null,
    statement: (r.statement ?? "").replace(/\s+/g, " ").trim(),
    inbox_source: r.source ?? null,
    adrs: adrs.filter((a) => (a.relates_to ?? []).includes(r.id) || (r.relates_to ?? []).includes(a.id))
      .map((a) => a.id).sort(),
    events: events.filter((e) => e.context === r.context).map((e) => e.id).sort(),
    scenarios: (scenarios[r.id] ?? []).sort(),
  }))
  .sort((a, b) => a.id.localeCompare(b.id));

const matrix = {
  _generated: HEADER,
  counts: {
    requirements: reqs.length,
    adrs: adrs.length,
    adrs_accepted: adrs.filter((a) => a.status === "accepted").length,
    events: events.length,
    inbox: inbox.length,
    inbox_promoted: inbox.filter((i) => i.promotes_to.length > 0).length,
  },
  requirements: rows,
  gaps: {
    requirements_without_scenarios: rows.filter((r) => r.scenarios.length === 0).map((r) => r.id),
    requirements_without_adr: rows.filter((r) => r.adrs.length === 0).map((r) => r.id),
    contexts_without_requirements: CONTEXTS.filter((c) => !reqs.some((r) => r.context === c)),
    inbox_unpromoted: inbox.filter((i) => i.promotes_to.length === 0).map((i) => i.file).sort(),
  },
};

await Deno.mkdir(`${ROOT}/traceability`, { recursive: true });
await Deno.writeTextFile(`${ROOT}/traceability/matrix.generated.json`, JSON.stringify(matrix, null, 2) + "\n");

// ── in-force ADR index ──────────────────────────────────────────────────────
const inForce = adrs
  .filter((a) => a.status === "accepted" && !a.superseded_by)
  .sort((a, b) => String(a.id).localeCompare(String(b.id)));
const proposed = adrs
  .filter((a) => a.status === "proposed")
  .sort((a, b) => String(a.id).localeCompare(String(b.id)));

let md = `<!-- ${HEADER} -->\n\n# Decisions in force\n\n`;
md += `Accepted and not superseded, as of the last \`deno task gen\`.\n\n`;
for (const a of inForce) {
  md += `## [${a.id}](${basename(a.file)}) — ${a.title ?? "(untitled)"}\n\n`;
  md += `**Contexts:** ${(a.contexts ?? []).join(", ") || "—"} · **Decided:** ${a.date ?? "—"}\n\n`;
  if (a.y) md += `> ${a.y}\n\n`;
}
md += `# Proposed, not yet in force\n\n`;
if (proposed.length === 0) {
  md += `None.\n`;
} else {
  md += `| ADR | Title | Review by | Blocked on |\n|---|---|---|---|\n`;
  for (const a of proposed) {
    const blockers = (a.relates_to ?? []).filter((x) => /^(HOT|OQ|SPIKE)-/.test(x)).join(", ") || "—";
    md += `| [${a.id}](${basename(a.file)}) | ${a.title ?? ""} | ${a.review_by ?? "**unset**"} | ${blockers} |\n`;
  }
}
await Deno.writeTextFile(`${ROOT}/adr/in-force.generated.md`, md);

console.log(`traceability/matrix.generated.json  ${rows.length} requirement(s)`);
console.log(`adr/in-force.generated.md           ${inForce.length} in force, ${proposed.length} proposed`);
