#!/usr/bin/env -S deno run --allow-read --allow-write
/**
 * Writes the generated artifacts:
 *   - traceability/matrix.generated.json   REQ <-> ADR <-> event <-> scenario <-> inbox source
 *   - adr/in-force.generated.md            accepted, not superseded
 *
 * DETERMINISTIC BY CONSTRUCTION. No timestamps, no clock reads, no map iteration order that
 * depends on the filesystem — CI runs this and fails on a diff, so any nondeterminism turns into
 * a permanently red build that looks like a stale file.
 */
import { parse as parseYaml } from "@std/yaml";
import { evaluateMilestones } from "./milestone-checks.ts";
import { CONTEXT_CODE_OF as CODE_OF, CONTEXTS } from "./contexts.ts";
import { walk } from "@std/fs";
import { basename, relative } from "@std/path";

const ROOT = new URL("..", import.meta.url).pathname.replace(/\/$/, "");
const rel = (p: string) => relative(ROOT, p);
/** Templates and previously-generated artifacts are never inputs — otherwise gen feeds on itself. */
const isTemplate = (p: string) =>
  basename(p).startsWith("_") || basename(p).includes(".generated.");

const HEADER = "GENERATED by tools/generate.ts — DO NOT EDIT. Run `deno task gen`.";

// Contexts and their codes: `tools/contexts.ts` is the single registry.

/**
 * YAML parses an unquoted `date: 2026-08-08` into a JS Date, and interpolating one renders it in
 * the RUNNER's timezone — "Fri Aug 07 2026 19:00:00 GMT-0500" on macOS vs "Sat Aug 08 2026
 * 00:00:00 GMT+0000" on a UTC CI box. That made this generator machine-dependent and the
 * stale-file gate caught it on the first CI run. Always reduce to a UTC calendar day.
 */
function ymd(v: unknown): string {
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  const s = String(v ?? "").trim();
  return s || "—";
}

function frontMatter(text: string) {
  const m = text.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
  if (!m) return null;
  try {
    return { fm: (parseYaml(m[1]) ?? {}) as Record<string, unknown>, body: m[2] ?? "" };
  } catch {
    return null;
  }
}

/** See validate.ts — `spikes/harness/node_modules` is on disk and invisible to `.gitignore`. */
const SKIP = [/[\\/]node_modules[\\/]/];

async function filesIn(dir: string, ext: string): Promise<string[]> {
  const out: string[] = [];
  try {
    for await (const e of walk(`${ROOT}/${dir}`, { exts: [ext], includeDirs: false, skip: SKIP })) {
      if (!isTemplate(e.path)) out.push(e.path);
    }
  } catch { /* absent */ }
  return out.sort();
}

// ── load ────────────────────────────────────────────────────────────────────
interface Req {
  id: string;
  statement?: string;
  source?: string;
  status?: string;
  priority?: string;
  relates_to?: string[];
}

const reqs: (Req & { context: string })[] = [];
const events: {
  id: string;
  name?: string;
  producer?: string;
  consumers?: string[];
  context: string;
}[] = [];

for (const ctx of CONTEXTS) {
  try {
    const y = parseYaml(await Deno.readTextFile(`${ROOT}/contexts/${ctx}/requirements.yaml`)) as
      | { requirements?: Req[] }
      | null;
    for (const r of y?.requirements ?? []) reqs.push({ ...r, context: ctx });
  } catch { /* absent */ }
  try {
    const y = parseYaml(await Deno.readTextFile(`${ROOT}/contexts/${ctx}/events.yaml`)) as
      | { events?: { id: string }[] }
      | null;
    for (const e of y?.events ?? []) events.push({ ...e, context: ctx } as (typeof events)[number]);
  } catch { /* absent */ }
}

const adrs: {
  id: string;
  title?: string;
  status?: string;
  date?: string;
  review_by?: string;
  contexts?: string[];
  relates_to?: string[];
  superseded_by?: string | null;
  supersedes?: string | null;
  y: string;
  file: string;
}[] = [];

for (const f of await filesIn("adr", ".md")) {
  const p = frontMatter(await Deno.readTextFile(f));
  if (!p) continue;
  // Y-statement: the first blockquote block after the front matter.
  const q = p.body.match(/(?:^|\n)((?:>[^\n]*\n?)+)/);
  const y = q
    ? q[1].split("\n").map((l) => l.replace(/^>\s?/, "").trim()).filter(Boolean).join(" ").trim()
    : "";
  adrs.push({ ...p.fm, y, file: rel(f) } as unknown as (typeof adrs)[number]);
}

const inbox: { file: string; title?: string; promotes_to: string[] }[] = [];
for (const f of await filesIn("inbox", ".md")) {
  const p = frontMatter(await Deno.readTextFile(f));
  if (!p) continue;
  const pt = p.fm.promotes_to;
  inbox.push({
    file: rel(f),
    title: p.fm.title as string | undefined,
    promotes_to: Array.isArray(pt) ? pt.map(String) : [],
  });
}

interface Hot {
  id: string;
  statement?: string;
  why_it_matters?: string;
  contexts?: string[];
  blocks?: string[];
  status?: string;
}
interface Oq {
  id: string;
  question?: string;
  owner?: unknown;
  decide_by?: unknown;
  blocks?: string[];
  status?: string;
}
interface Spike {
  id: string;
  question?: string;
  timebox?: string;
  closes_adr?: string;
  status?: string;
  exit_criteria?: unknown[];
}
interface Milestone {
  id: string;
  title?: string;
  depends_on?: string[];
  exit_criteria?: string[];
}

const hots: Hot[] =
  ((parseYaml(await Deno.readTextFile(`${ROOT}/hotspots.yaml`)) as { hotspots?: Hot[] })
    ?.hotspots) ?? [];
const oqs: Oq[] =
  ((parseYaml(await Deno.readTextFile(`${ROOT}/open-questions.yaml`)) as { open_questions?: Oq[] })
    ?.open_questions) ?? [];
const milestones: Milestone[] =
  ((parseYaml(await Deno.readTextFile(`${ROOT}/roadmap/milestones.yaml`)) as {
    milestones?: Milestone[];
  })
    ?.milestones) ?? [];
const glossary = ((parseYaml(await Deno.readTextFile(`${ROOT}/glossary.yaml`)) as {
  terms?: { term: string; definition?: string }[];
})?.terms) ?? [];

const spikes: Spike[] = [];
for (const f of await filesIn("spikes", ".md")) {
  const p = frontMatter(await Deno.readTextFile(f));
  if (p) spikes.push(p.fm as unknown as Spike);
}
spikes.sort((a, b) => String(a.id).localeCompare(String(b.id)));

/** TBD / empty / null all mean "nobody has decided this yet". */
const unset = (v: unknown) =>
  v === undefined || v === null || v === "" || String(v).trim() === "TBD";

// scenarios by REQ tag
const scenarios: Record<string, string[]> = {};
for (const f of await filesIn("contexts", ".feature")) {
  const text = await Deno.readTextFile(f);
  for (const m of text.matchAll(/@(REQ-[A-Z]{2,3}-\d{3})/g)) {
    (scenarios[m[1]] ??= []).push(rel(f));
  }
}

// ── matrix ──────────────────────────────────────────────────────────────────
const rows = reqs
  .map((r) => ({
    id: r.id,
    context: r.context,
    context_code: CODE_OF[r.context],
    status: r.status ?? null,
    priority: r.priority ?? null,
    statement: (r.statement ?? "").replace(/\s+/g, " ").trim(),
    inbox_source: r.source ?? null,
    adrs: adrs.filter((a) =>
      (a.relates_to ?? []).includes(r.id) || (r.relates_to ?? []).includes(a.id)
    )
      .map((a) => a.id).sort(),
    events: events.filter((e) => e.context === r.context).map((e) => e.id).sort(),
    scenarios: (scenarios[r.id] ?? []).sort(),
  }))
  .sort((a, b) => a.id.localeCompare(b.id));

const matrix = {
  _generated: HEADER,
  counts: {
    requirements: reqs.length,
    adrs: adrs.length,
    adrs_accepted: adrs.filter((a) => a.status === "accepted").length,
    events: events.length,
    inbox: inbox.length,
    inbox_promoted: inbox.filter((i) => i.promotes_to.length > 0).length,
  },
  requirements: rows,
  gaps: {
    requirements_without_scenarios: rows.filter((r) => r.scenarios.length === 0).map((r) => r.id),
    requirements_without_adr: rows.filter((r) => r.adrs.length === 0).map((r) => r.id),
    contexts_without_requirements: CONTEXTS.filter((c) => !reqs.some((r) => r.context === c)),
    inbox_unpromoted: inbox.filter((i) => i.promotes_to.length === 0).map((i) => i.file).sort(),
  },
};

await Deno.mkdir(`${ROOT}/traceability`, { recursive: true });
await Deno.writeTextFile(
  `${ROOT}/traceability/matrix.generated.json`,
  JSON.stringify(matrix, null, 2) + "\n",
);

// ── in-force ADR index ──────────────────────────────────────────────────────
const inForce = adrs
  .filter((a) => a.status === "accepted" && !a.superseded_by)
  .sort((a, b) => String(a.id).localeCompare(String(b.id)));
const proposed = adrs
  .filter((a) => a.status === "proposed")
  .sort((a, b) => String(a.id).localeCompare(String(b.id)));

let md = `<!-- ${HEADER} -->\n\n# Decisions in force\n\n`;
md += `Accepted and not superseded, as of the last \`deno task gen\`.\n\n`;
for (const a of inForce) {
  md += `## [${a.id}](${basename(a.file)}) — ${a.title ?? "(untitled)"}\n\n`;
  md += `**Contexts:** ${(a.contexts ?? []).join(", ") || "—"} · **Decided:** ${ymd(a.date)}\n\n`;
  if (a.y) md += `> ${a.y}\n\n`;
}
md += `# Proposed, not yet in force\n\n`;
if (proposed.length === 0) {
  md += `None.\n`;
} else {
  md += `| ADR | Title | Review by | Blocked on |\n|---|---|---|---|\n`;
  for (const a of proposed) {
    const blockers = (a.relates_to ?? []).filter((x) => /^(HOT|OQ|SPIKE)-/.test(x)).join(", ") ||
      "—";
    md += `| [${a.id}](${basename(a.file)}) | ${a.title ?? ""} | ${
      a.review_by ? ymd(a.review_by) : "**unset**"
    } | ${blockers} |\n`;
  }
}
await Deno.writeTextFile(`${ROOT}/adr/in-force.generated.md`, md);

// ── STATUS.generated.md ─────────────────────────────────────────────────────
// Deliberately clock-free. Whether a decide_by has PASSED is `deno task validate`'s job — it
// writes nothing, so it may read the real clock. If this file computed "overdue", it would change
// on its own and the CI stale-file gate would go red on unrelated pushes.

// drops awaiting ingest
let dropsPending = 0;
try {
  for await (const e of Deno.readDir(`${ROOT}/research-drop`)) {
    if (!e.isFile || !e.name.endsWith(".md") || e.name.startsWith("_")) continue;
    const p = frontMatter(await Deno.readTextFile(`${ROOT}/research-drop/${e.name}`));
    if (String(p?.fm.status ?? "unprocessed") !== "ingested") dropsPending++;
  }
} catch { /* absent */ }

const oqBlocked = oqs.filter((q) => unset(q.owner) || unset(q.decide_by));
// erp-spec#7: `oqBlocked` answers "does it have an owner?", which is NOT what "undecided" means.
// Reporting it under a heading that asks what is undecided printed "None" over five genuinely open
// questions, two of which block a written posting rule. Openness is `status`.
const oqOpen = oqs.filter((q) => String(q.status ?? "open") === "open");
const oqAnswered = oqs.filter((q) => String(q.status ?? "open") === "answered");
const hotOpen = hots.filter((h) => (h.status ?? "open") === "open");
const spikeOpen = spikes.filter((s) => (s.status ?? "open") !== "closed");
const glossTodo = glossary.filter((t) => String(t.definition ?? "").trim() === "TODO");
const oneLine = (s: unknown) => String(s ?? "").replace(/\s+/g, " ").trim();
const trunc = (s: string, n: number) => (s.length > n ? s.slice(0, n - 1).trimEnd() + "…" : s);

let st = `<!-- ${HEADER} -->\n\n# Status\n\n`;
st +=
  `Point-in-time view of every open thread. Regenerated by \`deno task gen\`; never edited.\n\n`;
st +=
  `**This file reads no clock.** Dates below are what was written down — whether one has passed\n`;
st += `is \`deno task validate\`'s judgement, not this file's.\n\n`;

st += `## At a glance\n\n`;
st += `| | Count | |\n|---|---:|---|\n`;
st +=
  `| Open questions | ${oqOpen.length} open | ${oqAnswered.length} answered of ${oqs.length} · **${oqBlocked.length} with no owner or no decide-by** |\n`;
st += `| Conflicts (HOT) | ${hots.length} | ${hotOpen.length} open |\n`;
st +=
  `| Decisions (ADR) | ${adrs.length} | ${inForce.length} in force · ${proposed.length} proposed |\n`;
st += `| Spikes | ${spikes.length} | ${spikeOpen.length} open |\n`;
st += `| Requirements | ${reqs.length} | ${
  rows.filter((r) => r.scenarios.length === 0).length
} without a scenario |\n`;
st += `| Inbox | ${inbox.length} | ${
  inbox.filter((i) => i.promotes_to.length === 0).length
} unpromoted |\n`;
st += `| Drops awaiting \`deno task ingest\` | ${dropsPending} | |\n`;
st += `| Glossary terms | ${glossary.length} | ${glossTodo.length} still \`TODO\` |\n\n`;

st += `## The bottleneck: undecided questions\n\n`;
if (oqOpen.length === 0) {
  st += `None — every question carries an answer.\n\n`;
} else {
  st += `**${oqOpen.length} of ${oqs.length} still open**, soonest decide-by first.`;
  st += oqBlocked.length > 0
    ? ` ${oqBlocked.length} have no owner or no decide-by date.\n\n`
    : `\n\n`;
  st += `| OQ | Question | Owner | Decide by | Blocks |\n|---|---|---|---|---|\n`;
  // Sorted on the calendar day, never on the rendered string: an unquoted YAML date is a JS Date
  // and `String()` on one renders in the runner's timezone. `ymd` reduces it for display; this
  // sorts on the same reduction so the order cannot go machine-dependent either.
  const byDate = [...oqOpen].sort((a, b) =>
    (ymd(a.decide_by) + a.id).localeCompare(ymd(b.decide_by) + b.id)
  );
  for (const q of byDate) {
    st += `| \`${q.id}\` | ${trunc(oneLine(q.question), 90)} | ${
      unset(q.owner) ? "**unset**" : oneLine(q.owner)
    } | ${unset(q.decide_by) ? "**unset**" : ymd(q.decide_by)} | ${
      (q.blocks ?? []).map((b) => `\`${b}\``).join(" ") || "—"
    } |\n`;
  }
  st +=
    `\nWhether any of these dates has PASSED is \`deno task validate\`'s judgement — gate 7 fails `;
  st += `on an open question past its decide-by. This file reads no clock and so cannot say.\n\n`;
}

st += `## Open conflicts\n\n`;
if (hotOpen.length === 0) st += `None.\n\n`;
else {
  st += `| HOT | Statement | Blocks |\n|---|---|---|\n`;
  for (const h of hotOpen) {
    st += `| \`${h.id}\` | ${trunc(oneLine(h.statement), 110)} | ${
      (h.blocks ?? []).map((b) => `\`${b}\``).join(" ") || "—"
    } |\n`;
  }
  st += `\n`;
}

st += `## Decisions\n\n### In force (${inForce.length})\n\n`;
for (const a of inForce) st += `- \`${a.id}\` — ${a.title ?? ""}\n`;
st += `\n### Proposed (${proposed.length})\n\n`;
if (proposed.length === 0) st += `None.\n\n`;
else {
  st += `| ADR | Title | Review by | Blocked on |\n|---|---|---|---|\n`;
  for (const a of proposed) {
    const blockers = (a.relates_to ?? []).filter((x) => /^(HOT|OQ|SPIKE)-/.test(x));
    st += `| \`${a.id}\` | ${a.title ?? ""} | ${a.review_by ? ymd(a.review_by) : "**unset**"} | ${
      blockers.map((b) => `\`${b}\``).join(" ") || "—"
    } |\n`;
  }
  st += `\n`;
}

st += `## Spikes\n\n`;
st += `| Spike | Question | Timebox | Closes | Status |\n|---|---|---|---|---|\n`;
for (const s of spikes) {
  st += `| \`${s.id}\` | ${trunc(oneLine(s.question), 80)} | ${s.timebox ?? "—"} | ${
    s.closes_adr === "new" ? "_new ADR_" : `\`${s.closes_adr ?? "—"}\``
  } | ${s.status ?? "open"} |\n`;
}
st += `\n## Roadmap\n\n`;
// Clock-free: `adr_review_by_current` needs today's date, so it reports as `validate` here and is
// decided by `deno task validate`, which writes nothing and may read the real clock.
const ms = await evaluateMilestones(ROOT, null);
st +=
  `**\`prose\` is not \`met\`.** A criterion no tool can decide is one somebody has to assert —\n`;
st +=
  `it is counted separately on purpose, and a milestone is not done because its checkable half is.\n\n`;
st +=
  `| Milestone | Title | Depends on | met | unmet | prose | validate |\n|---|---|---|---:|---:|---:|---:|\n`;
for (const m of ms) {
  st += `| \`${m.id}\` | ${m.title} | ${
    m.depends_on.map((d) => `\`${d}\``).join(" ") || "—"
  } | ${m.met} | ${m.unmet || "—"} | ${m.prose || "—"} | ${m.deferred || "—"} |\n`;
}
const unmetAll = ms.flatMap((m) =>
  m.criteria.filter((c) => c.verdict === "unmet").map((c) => ({ m, c }))
);
st += `\n### Machine-checkable criteria not yet met (${unmetAll.length})\n\n`;
if (unmetAll.length === 0) st += `None.\n`;
else {
  st += `| Milestone | Criterion | Check | Measured |\n|---|---|---|---|\n`;
  for (const { m, c } of unmetAll) {
    st += `| \`${m.id}\` | ${trunc(oneLine(c.text), 70)} | \`${c.check}\` | ${c.detail} |\n`;
  }
}

st += `\n## Coverage gaps\n\n`;
const gapCtx = matrix.gaps.contexts_without_requirements;
const gapScn = matrix.gaps.requirements_without_scenarios;
st += `- Contexts with no requirements yet: ${
  gapCtx.length ? gapCtx.map((c) => `\`${c}\``).join(", ") : "none"
}\n`;
st += `- Requirements with no Gherkin scenario: ${
  gapScn.length ? gapScn.map((c) => `\`${c}\``).join(", ") : "none"
}\n`;
st += `- Glossary terms still \`TODO\`: ${
  glossTodo.length ? glossTodo.map((t) => `\`${t.term}\``).join(", ") : "none"
}\n`;

await Deno.writeTextFile(`${ROOT}/STATUS.generated.md`, st);

// ── spec-map.generated.opml ─────────────────────────────────────────────────
// OPML 2.0. MindNode Next imports it, as do Xmind, OmniOutliner, Freeplane and most outliners —
// chosen over MindNode's own format so the map is not locked to one app.
//
// One-way by construction: this is a VIEW. Rearranging the map in MindNode and re-running
// `deno task gen` discards the rearrangement. Edit the YAML, regenerate the map.
const esc = (s: unknown) =>
  String(s ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/\s+/g, " ").trim();

type Node = { text: string; note?: string; children?: Node[] };

const tree: Node = {
  text: "CFS ERP — spec-v1",
  note: "Generated view of erp-spec. Edit the YAML, not the map.",
  children: [
    {
      text: `Roadmap (${milestones.length})`,
      children: milestones.map((m) => ({
        text: `${m.id} — ${m.title ?? ""}`,
        note: `depends on: ${(m.depends_on ?? []).join(", ") || "nothing"} · ${
          (m.exit_criteria ?? []).length
        } exit criteria`,
        children: (m.exit_criteria ?? []).map((c) => ({ text: oneLine(c) })),
      })),
    },
    {
      text: `Open questions (${oqOpen.length} of ${oqs.length} still open)`,
      note: "The bottleneck. Each blocks what is listed under it.",
      children: oqs.map((q) => ({
        text: `${q.id} — ${trunc(oneLine(q.question), 100)}`,
        note: `owner: ${unset(q.owner) ? "UNSET" : oneLine(q.owner)} · decide by: ${
          unset(q.decide_by) ? "UNSET" : ymd(q.decide_by)
        }`,
        children: (q.blocks ?? []).map((b) => ({ text: `blocks ${b}` })),
      })),
    },
    {
      text: `Conflicts (${hotOpen.length} open)`,
      children: hots.map((h) => ({
        text: `${h.id} — ${trunc(oneLine(h.statement), 100)}`,
        note: oneLine(h.why_it_matters),
        children: (h.blocks ?? []).map((b) => ({ text: `blocks ${b}` })),
      })),
    },
    {
      text: `Decisions (${inForce.length} in force, ${proposed.length} proposed)`,
      children: [
        {
          text: `In force (${inForce.length})`,
          children: inForce.map((a) => ({ text: `${a.id} — ${a.title ?? ""}`, note: a.y })),
        },
        {
          text: `Proposed (${proposed.length})`,
          children: proposed.map((a) => ({
            text: `${a.id} — ${a.title ?? ""}`,
            note: `review by: ${a.review_by ? ymd(a.review_by) : "UNSET"} · ${a.y}`,
            children: (a.relates_to ?? []).filter((x) => /^(HOT|OQ|SPIKE)-/.test(x)).map((b) => ({
              text: `blocked on ${b}`,
            })),
          })),
        },
      ],
    },
    {
      text: `Spikes (${spikeOpen.length} open)`,
      children: spikes.map((s) => ({
        text: `${s.id} — ${trunc(oneLine(s.question), 100)}`,
        note: `timebox: ${s.timebox ?? "—"} · closes: ${
          s.closes_adr === "new" ? "a new ADR" : s.closes_adr ?? "—"
        } · ${s.status ?? "open"}`,
        children: (s.exit_criteria ?? []).map((c) => ({ text: oneLine(c) })),
      })),
    },
    {
      text: `Contexts (${CONTEXTS.length})`,
      children: CONTEXTS.map((c) => {
        const cr = reqs.filter((r) => r.context === c);
        const ce = events.filter((e) => e.context === c);
        return {
          text: `${c} (${CODE_OF[c]})`,
          note: `${cr.length} requirement(s) · ${ce.length} event(s)`,
          children: [
            ...cr.map((r) => ({ text: `${r.id} — ${trunc(oneLine(r.statement), 100)}` })),
            ...ce.map((e) => ({
              text: `${e.id} — ${e.name ?? ""}`,
              note: `${e.producer ?? "?"} → ${(e.consumers ?? []).join(", ") || "terminal"}`,
            })),
          ],
        };
      }),
    },
    {
      text: `Capture (${
        inbox.filter((i) => i.promotes_to.length === 0).length
      } unpromoted of ${inbox.length})`,
      note: dropsPending
        ? `${dropsPending} drop file(s) awaiting \`deno task ingest\``
        : "no drops pending",
      children: inbox.filter((i) => i.promotes_to.length === 0).map((i) => ({
        text: trunc(oneLine(i.title ?? i.file), 100),
        note: i.file,
      })),
    },
  ],
};

const renderNode = (n: Node, depth: number): string => {
  const pad = "  ".repeat(depth);
  const attrs = `text="${esc(n.text)}"${n.note ? ` _note="${esc(n.note)}"` : ""}`;
  if (!n.children?.length) return `${pad}<outline ${attrs}/>\n`;
  return `${pad}<outline ${attrs}>\n${
    n.children.map((c) => renderNode(c, depth + 1)).join("")
  }${pad}</outline>\n`;
};

const opml = `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${HEADER} -->
<opml version="2.0">
  <head>
    <title>CFS ERP spec</title>
  </head>
  <body>
${renderNode(tree, 2)}  </body>
</opml>
`;
await Deno.writeTextFile(`${ROOT}/spec-map.generated.opml`, opml);

console.log(`traceability/matrix.generated.json  ${rows.length} requirement(s)`);
console.log(
  `adr/in-force.generated.md           ${inForce.length} in force, ${proposed.length} proposed`,
);
console.log(
  `STATUS.generated.md                 ${oqOpen.length} open, ${hotOpen.length} conflicts open`,
);
console.log(`spec-map.generated.opml             ${opml.split("<outline").length - 1} nodes`);
